### ISSUE TITLE
It is an issue really!!

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#101]
Hey @all-contributors please add @soichih  for code design ideas maintenance test

**Comment by yarikoptic** [comment]
Hm, I insist
Hey @all-contributors please add @soichih for code design ideas maintenance test

**Comment by soichih** [comment]
Thanks @yarikoptic !!

**Comment by yarikoptic** [comment]
Pleasure was mine! ;-)
