### ISSUE TITLE
Remove DataLad or add more projects to new ui

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#107]
@soichih - thanks for keeping datalad logo in the be design but I think we should either remove it or add brainlife, con, and any other related to the contributors project ;-)

**Comment by soichih** [comment]
Well, the page looks kind of boring without that logo.. :) 

Also, you've been doing all that volunteering work so I think it's appropriarte to show who is behind it? I think I might sneak in brainlifelog next to it.. if you don't mind :) I don't think anyone would care that it's there though..

We should add other logos from other projects also!

**Comment by yarikoptic** [comment]
ok, brainlife is added, I will leave to others to add more projects as they will @emdupre @effigies @rmarkello @adswa via PRs
