### ISSUE TITLE
in room.html version of jitsi invocation jitsi nickname does not persist

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#109]
I keep joining as anonymous, need to retype my nickname if I want to participate in chat.  I think it has smth with invocation of jitsi room via API vs just a URL (there even in a room where I have never been my known name is used).

**Comment by soichih** [comment]
I am not having this problem using Google Chrome or Firefox on Ubuntu20

![image](https://user-images.githubusercontent.com/923896/86030690-cc639280-ba02-11ea-8571-a46da6e38819.png)

When I login, it shows "Fellow jitsi.." for like 1 seconds and get automatically reset to my name. Are you using any plugin / privacy protection type features?

**Comment by yarikoptic** [comment]
Great to hear that it generally works! For me it just keeps saying "me"... I wonder if any of those messages in the console be relevant somehow:
```
external_api.js:315 Unrecognized feature: 'display-capture'.
_createIFrame @ external_api.js:315
LocalStatsCollector.js:22 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ LocalStatsCollector.js:22
Logger.js:154 2020-06-29T16:36:23.426Z [features/local-recording] <Object._loadMetadata>:  Failed to parse localStorage item.
o @ Logger.js:154
Logger.js:154 2020-06-29T16:36:23.776Z [modules/UI/videolayout/VideoLayout.js] <Object.changeUserAvatar>:  Missed avatar update - no small video yet for undefined
o @ Logger.js:154
favicon.ico:1 Failed to load resource: the server responded with a status of 404 (File not found)
index.js:9 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ index.js:9
index.js:9 falling back to ArrayBuffer instantiation
```

**Comment by yarikoptic** [comment]
ok -- it seems to be cookies!  Because it is external services, chrome did block cookies from jit.si and meet.jit.si -- I had to explicitly allow and then my name started to persist... I guess if someone else complains, we would need to start a FAQ. Closing for now
