### ISSUE TITLE
vue interface: "auto loading"

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#110]
New interface is awesome @soichih !  But loading all the posters into the page is really taxing on the browser.   I have little to no clue in howto but I know that it is possible to implement autoloading of "next" posters when you scroll down. 
I vaguely remember that @akeshavan has done something like that in... OMG -- posters browser (or  recommendation engine) for OHBM201?.  What was it and where is it @akeshavan?  May be we could reuse some other ideas from that effort here as well.

Note: [new vue interface](https://datalad-datasets.github.io/ohbm2020-posters/index_beta.html#/) is linked from the [original default](https://datalad-datasets.github.io/ohbm2020-posters/) one.

**Comment by soichih** [comment]
Yep.. I've done little on the performance optimization.. I will do that this morning.

**Comment by yarikoptic** [comment]
I think #115 fixed it!
