### ISSUE TITLE
vue interface: where is brainlife?

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#111]
I see that it was added in
https://github.com/datalad-datasets/ohbm2020-posters/pull/108/commits/583c3b2ea294b3830f484abd34e4b9e4cd77950c#diff-d0b08210691d5d90ecf9d04a58ba5e7dR5
but I do not see it on https://datalad-datasets.github.io/ohbm2020-posters/index_beta.html#/

**Comment by yarikoptic** [comment]
fixed, probably by #115

**Comment by soichih** [comment]
I think the logo is there now? I think gh-pages's CDN is pretty slow to propagate.. so maybe that's what's causing it?

**Comment by yarikoptic** [comment]
nah, I think I tested locally as well -- likely smth else which was resolved (e.g. via recompile or whatnot)
