### ISSUE TITLE
TODO: tweet about new UI available

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#112]
IIRC it is @soichih @emdupre and @rmarkello to praise?  Please assign yourself and tweet! ? ;)

**Comment by rmarkello** [comment]
As much as I'd _like_ to have been involved, all credit goes to @emdupre and @soichih !

**Comment by emdupre** [comment]
Valentina beat me to tweeting, but I quote-tweeted to highlight @soichih's work !

https://twitter.com/emdupre_/status/1277610286443364353?s=20

**Comment by yarikoptic** [comment]
I think with the tweets out we can close this one ;-)
