### ISSUE TITLE
Switch to new UI

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#113]
I think we should first 

- [x] resolve #110 to make it just a bit more fluid
- [x] test it more
- ideally #116 to be resolved too but I am ok for the switch to happen without that
- [x] send a PR to 
      - rename index.html to `index_orig.html`
      - rename `index_new.html` to index.html and may be somewhere a link to the old UI
      - provide `index_new.html` with a redirect to `index.html`

**Comment by soichih** [comment]
I am going to switch index.html and index_beta.html around with my next PR!

**Comment by soichih** [comment]
I missed this one >  "may be somewhere a link to the old UI". I will include it somewhere for the next round of update.
