### ISSUE TITLE
vue ui: for missing posters add a URL and change image

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#116]
ATM it just cycles back to the page, instead of going here into PRs, or may be better it should go into [edit overrides](https://github.com/datalad-datasets/ohbm2020-posters/edit/gh-pages/posters-overrides.json) page right away?  Also instead of gray square (also present while loading) - be some dedicated image (gray with "Submit a PR" phrase or alike)

**Comment by soichih** [comment]
Something like..
![image](https://user-images.githubusercontent.com/923896/86024187-acc86c00-b9fa-11ea-9a55-df7f4d272316.png)
?
clicking it will go to the overrides.json edit page.

**Comment by yarikoptic** [comment]
yeap yeap, thanks!
