### ISSUE TITLE
make names, categories, etc in poster items to be "fed" into search to limit posters for chosen "thing"

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#119]
that would make navigation of the posters collections even better and should be quite easy to do I guess for those who know JS/vue ;-)

**Comment by soichih** [comment]
The search filter should be searching across most of those fields already. Maybe it's not working right? 

The way it works is that.. search text will be split into "search token", then for each token find posters that matches all tokens somewhere in the poster information.

https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/ui/src/components/Home.vue#L227

Oh, and the whole thing is done in a case-insensitive way. Is there a different logic we should try?

**Comment by soichih** [comment]
Actually, it's not doing what I just described .. Looking now

**Comment by soichih** [comment]
Fixed. I will work on the other items before rebuilding / sending PR

**Comment by yarikoptic** [comment]
ok, may be PR would fix that (will wait for it to try), or may be I just have not described my desires well: have any phrase/author in each poster rendering to be "clickable" to feed the "search"..

**Comment by soichih** [comment]
Oh~ I get it now.. I will add that mechanism.

**Comment by soichih** [comment]
Implemented. Looking for other ones..

**Comment by yarikoptic** [comment]
I am refreshing PRs page every minute ;)

**Comment by soichih** [comment]
Sorry, I've been staring at this > https://github.com/datalad-datasets/ohbm2020-posters/issues/120 for the last 5 minutes.

**Comment by yarikoptic** [comment]
done in #121
