### ISSUE TITLE
Move "Video Chat" to appear when hovering over poster preview (at the bottom of it?)

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#120]
- may be also with an explicit PDF icon as well -- I already went to some PDFs when I actually wanted video chat
- also will be needed for #119 to work properly (ATM it would occlude an author)

**Comment by soichih** [comment]
So.. you want a dedicated button to open the PDF? Instead of letting user click on the thumbnail?

**Comment by yarikoptic** [comment]
yes, to make it more obvious and consistent.  FWIW -- underlying image could still have "open PDF" action ;-)

**Comment by yarikoptic** [comment]
but that might interfere abit with imprecise clicks on "Video Chat" so might be better just to be explicit.  Possibly other actions could be added later ("Join Chat") or just in the future ;-)

**Comment by yarikoptic** [comment]
Also people asked (#63 ?) for additional "media" to be linked like videos - might be the right place to add

**Comment by soichih** [comment]
OK. I will update to this for now.

![image](https://user-images.githubusercontent.com/923896/86033828-907efc00-ba07-11ea-9a31-750bd70f538c.png)

**Comment by yarikoptic** [comment]
Well, one of the points was to avoid covering Authors, and "Video Chat" in above would still do that.  Why not to move it to appear above poster image?

**Comment by soichih** [comment]
OK. I will rearrange things a bit

**Comment by yarikoptic** [comment]
fixedin #121
