### ISSUE TITLE
An alternative to "Yarik's amazing" name for **our** posters platform

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#135]
It was "mine" only for a short period of time, and current UI is definitely not mine ;) 
I would like to contact OHBM asking to adjust that button (if still possible) and future references to our project to something else.  Any ideas?  e.g. could be "CONmazing poster viewing tool" to refer to the http://centerforopenneuroscience.org/ booth of which I host at OHBM... Could refer to open science SIG since it is in its spirit etc.
Ideas? @christian-monch @nicholst @effigies @rmarkello @adswa @sofievdbos @bpoldrack @emdupre @soichih @r03ert0

**Comment by adswa** [comment]
If you want to get your name out of it, how about replacing it with "OSSIG & friends"?
"OSSIG & friends' amazing poster viewing tool"
Or:
"OS-SIG & friends' grass-root-initiative poster registry"
Or (my favourite, but too snarky :wink:)
"Click here for something that actually works well"

**Comment by yarikoptic** [comment]
;-) but probably ideally it should be shorter, not longer than what it is now.  Could also be some amalgamation of participated projects/entities, e.g. "DataLife Posters Registry" or "BrainLad Posters Registry" ;)

**Comment by yarikoptic** [comment]
or just "Posters Open Virtual Portal" (since it is not just about viewing and not a tool)

**Comment by effigies** [comment]
Gallery (by Open-Science SIG) of Interactive Presentations (GOSSIP)

**Comment by effigies** [comment]
Some more:

* DataLife Interactive Poster Hall - DIPH (diff)
* DataLife Online Poster Hall - DOPH (doff)
* Scientific Online Poster Hall and Open Meeting Rooms - SOPHOMR (sophomore)
  * Could fiddle with this for aesthetics. SOPHMR probably works better. I can't see how to get all the way to SOPHOMORE.
* BrainLad/CON Listing of Interactive Posters - BLIP/CLIP
* Open Poster Interactive Environment - OPIE
* CON/DataLife/HBM/Neat Open Poster Environment - COPE/DOPE/HOPE/NOPE
* GIPH Interactive Poster Hall - GIPH (pronounced: GIF)
* Searchable Poster Session Site - SPSS
* Registry - R

Also, Poster can be replaced with Presentation for most of these.

**Comment by soichih** [comment]
Clever! I like CLIP. It's snappy! And DOPE is just as good.

Although.. I really like "Yarik's amazing poster tool" :) I mean.. why not!?

**Comment by yarikoptic** [comment]
@effigies -- now I feel sad to suck this badly -- you came up with so many good ones! Bravo!  I like many of them for their wit.  SPSS -- just love it.  Sure thing CLIP and DOPE are also fun.  But GOSSIP is meaningful but itself, and has an expanded name which could outlive this particular OHBM ;-)  SOPHOMR - also super nice... let us sleep on all the wonderful choices we have now ;)  Should we may be run a twitter poll?!

@soichih THANKS! but I think it would be not FAIR and it doesn't abbreviate well (YAPT -- bleh) ;)

**Comment by yarikoptic** [comment]
replacing Poster with Presentation would just put the final nail into the coffin - just add session times (may be crowdcast instead of jitsi for those but we could run our own jitsi with policies set), chat we will come up with, export of the calendar, and tada -- we have a complete, albeit simplistic, system for a conference! ;)

**Comment by nicholst** [comment]
+1 for "Gallery (by Open-Science SIG) of Interactive Presentations (GOSSIP)" and anything that references OS-SIG as I do feel that is a thread that links many contributors.

**Comment by bpoldrack** [comment]
> @soichih THANKS! but I think it would be not FAIR and it doesn't abbreviate well (YAPT -- bleh) ;)

Somehow I doubt anybody but you cares for the first aspect and I can fix the second one:
"Yarik's incredible poster engagement environment" - YIPEE ;-)

Otherwise: +1 for GOSSIP

**Comment by yarikoptic** [comment]
Thanks @bpoldrack ! Now I do have a name for some next project if yippe is overwhelmed by gossip

**Comment by yarikoptic** [comment]
So, top candidates in alphabetical order:

- :+1:  CLIP: CON Listing of Interactive Posters
- :eyes: DOPE: Data(Lad/Brain)Life Open Poster Environment
- :rocket: GOSSIP: Gallery (by Open-Science SIG) of Interactive Presentations
- :heart:  SOPHOMR: Scientific Online Poster Hall and Open Meeting Rooms
- :smile: YIPEE: Yarik's incredible poster engagement environment

so may be we could run a quick twitter poll or should we just decide in-house?

**Comment by effigies** [comment]
I feel like we should decide in house. Mostly because I think, on Twitter, whimsy among the disinterested will gravitate toward YIPEE. I'm okay if it goes that way, but it's the Boaty McBoatface of the set, which makes it feel forgone in a general poll.

**Comment by emdupre** [comment]
I'm also +1 on polling in-house, though I'd add that if we're leaning towards a name with OSSIG in it we should probably ask the OSSIG that it's ok with them, just to be sure :smile_cat:

**Comment by yarikoptic** [comment]
ok, inhouse then it is -- updated list above with icons - please vote

**Comment by yarikoptic** [comment]
multiple votes are ok with me, unless you decide that they are not ;)

**Comment by yarikoptic** [comment]
Thanks everyone! So let's ask ossig people, I guess just the committee?

**Comment by sofievdbos** [comment]
I guess we can ask the committee chair & ask her who all the OSSIG people are? :)

**Comment by Remi-Gau** [comment]
We listed them here. :-)

https://ossig.netlify.app/

Do you want me to bring this issue to their attention in our mattermost channel?

**Comment by effigies** [comment]
That might be quickest.

**Comment by yarikoptic** [comment]
@Remi-Gau did you do it or should I ?

**Comment by emdupre** [comment]
I checked in and there's some light concern that the OSSIG officers weren't heavily involved, so they don't want to take over the branding. There was a suggestion to replace "SIG" with "Community" -- so GOSCIP. Not quite the same, but I still like it !

**Comment by effigies** [comment]
Open Science...

* Syndicate
* Society
* Synod
* Soviet
* Sympathizers
* Subculture
* ...?

Can also move to Z to be sure it's pronounced with a sibilant rather than a plosive:

* Zealots

**Comment by yarikoptic** [comment]
thanks for suggestions @effigies ... Anything else but SIG goes away from the original purpose of this acronym unless we establish one more "community" or SIG. 
If anything, I would then prefer it being associated with [CON](http://centerforopenneuroscience.org/) (and thus without explicit Y in it) to which I invite all of you who participated to "join" to be listed among collaborators: http://centerforopenneuroscience.org/whoweare#collaborators_ . A sample PR  to follow: https://github.com/con/centerforopenneuroscience.org/pull/26

I think the "playfield" is open again :-( BTW -- @vsoch tends to come up with awesome names for the projects (e.g. a brand new https://github.com/con/tributors), may be she has some ideas too...

**Comment by yarikoptic** [comment]
could be `con/ference` ;-)

**Comment by yarikoptic** [comment]
oh hoh: https://www.urbandictionary.com/define.php?term=ference

ference - a word used after a simple statement showing that all is well.
(not to be overused)
the international sign is represented by taking your pointer finger and thumb and smashing them together.

So it even comes with a "LOGO"

**Comment by rmarkello** [comment]
I like `con/ference`! 

(But it's probably best not to rely on Urban Dictionary definitions, especially given the recent attempts of white supremacists to [co-opt that hand gesture](https://www.adl.org/education/references/hate-symbols/okay-hand-gesture) 😒).

**Comment by yarikoptic** [comment]
Ok, forget about that logo, although my tired brain took "smashing them together" not the same way as "make an O", but literally smashing together, so I thought it was different than Ok sign (which made little sense) ;)

**Comment by yarikoptic** [comment]
so we would need just 2 more votes to beat YIPPE and then can announce it to be a `con/ference` ;)

**Comment by effigies** [comment]
I'm good with con/ference.

**Comment by yarikoptic** [comment]
@effigies please "vote" on https://github.com/datalad-datasets/ohbm2020-posters/issues/135#issuecomment-652486445 (I think better to not mix it into original poll)

**Comment by vsoch** [comment]
I am in full support of looking up the con- prefix in the dictionary and creating absolutely every possible software that might be a fun name!

**Comment by Remi-Gau** [comment]
> I am in full support of looking up the con- prefix in the dictionary and creating absolutely every possible software that might be a fun name!

French speakers might have an interesting opinion about the `con` prefix but I am cool with it.

**Comment by vsoch** [comment]
Haha, I just looked it up, oh dear! For spanish, it just means "with" so it's not so bad.

**Comment by effigies** [comment]
I'm just going to keep doing this until Yarik closes the issue:

* GallOP - Gallery of Open Presentations
* GRIP - Gallery and Registry of Interactive Presentations
* DRIP - Dynamic Registry of Interactive Presentations
* FLIP/FLOP - FAIR Listing of Interactive/Open Presentations
* PLOS - Presentation Library of Open Science
* CLAMP - CON Listing of Active Media Presentations
* WOMP - WOMP Open Media Presentations
* YODA - YODA's Open Demonstration Agora
* COMPRESS - CON Open Media Presentation Registry and Electronic Sorting System
* HIPPIE - HBM-Initiated Poster Presentation Interactive Environment
* DR LISP - Discussion Rooms for Live Interactive Scientific Presentations

Some `con-` suggestions:

* con/fide - FAIR Interactive Demonstration Environment
* con/sider - Scientific Interactive Demonstration Environment Registry
* con/tent - The logo practically draws itself.
* con/sensus
* con/viviality
* con/centrate
* con/centric
* con/spicuous
* con/dense

**Comment by nicholst** [comment]
+1 for GallOP - Gallery of Open Presentations

**Comment by yarikoptic** [comment]
Damn you @effigies!  Please stop!  I love GallOP (might also be Gallery of Open Posters), I think it better reflects the platform ATM, and I think that if `con/ference` comes about it could use (or build atop) this component!  So the very final vote (@effigies - just click, don't type!!!)

- :+1: con/ference
- :heart: GallOP
- :smile: YIPPE (for the contrast and since it is was the closest next contender ;))

 @christian-monch @nicholst @effigies @rmarkello @adswa @sofievdbos @bpoldrack @emdupre @soichih @r03ert0

**Comment by r03ert0** [comment]
HOP: House of Posters (or Hall, but House...)

**Comment by yarikoptic** [comment]
Woohoo! congratulations -- decided "GallOP - Gallery of Open Presentations" it is.  I will quickly tune up header of README.md and inform OHBM, but repo for now will stay to not break anything ;-)

**Comment by soichih** [comment]
Now we need a LOGO~

**Comment by effigies** [comment]
Should we rebrand the page to get GallOP on it before the final poster session?

**Comment by yarikoptic** [comment]
I would not fully rebrand (change title) but do reference GallOP where we point to this repo URL. Something like "Powered by GallOP"
