### ISSUE TITLE
some pdf previews need explicit "white background"

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#138]
see e.g. 1559 1925

**Comment by yarikoptic** [comment]
ok, now we have https://github.com/datalad-datasets/ohbm2020-posters-pdfs datalad dataset with all PDFs it could obtain under annex.  I now want to (re)generate all previews within https://github.com/datalad-datasets/ohbm2020-posters-thumbnails having this pdfs dataset as a subdataset -- YODA all the way ;)  I will send a PR there and while at it, I will look to address this background issue. attn @soichih

**Comment by yarikoptic** [comment]
FWIW -- fix is to add `-flatten` since `-background` is just a modifier... I am regenerating them all but we might want to rewrite history there to get only new ones in objects or it would be too large.  BTW -- where do we use big ones?

**Comment by soichih** [comment]
I've regenerated all x200 thumbs with `-flatten layers`. There should no longer be a black background.

I've also wiped the histrory and removed x1200 thunmbs. `.git` is now 49M.

**Comment by yarikoptic** [comment]
Awesome! I will close this adding it is fixed, will check later
