### ISSUE TITLE
Some wrong attendance counts might be from mobile

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#153]
I think I have tried to show from the phone and it incremented but didn't decrement since I think I didn't actually start app

**Comment by soichih** [comment]
Unm... I wasn't aware that mobile version woul ask user before it opens the meeting room..

![Screenshot_20200701-104128](https://user-images.githubusercontent.com/923896/86263239-f21da280-bb8e-11ea-8b6e-f2a7ffd86608.png)

What this means is that.. we need to wait for user to actually enter the room, and start sending the ping.. which I think we can do by handling `videoConferenceJoined` event.. I will test this.
