### ISSUE TITLE
Provide more guidance about how to submit a PR with changes

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#20]
Probably in README.md.  Could also point to how edit `posters-overrides.json` directly on github.

**Comment by jaetzel** [comment]
[OHBM2020_Poster1930_Etzel_b.pdf](https://github.com/datalad-datasets/ohbm2020-posters/files/4827285/OHBM2020_Poster1930_Etzel_b.pdf)

**Comment by yarikoptic** [comment]
> [OHBM2020_Poster1930_Etzel_b.pdf](https://github.com/datalad-datasets/ohbm2020-posters/files/4827285/OHBM2020_Poster1930_Etzel_b.pdf)

oh.... I wonder if it would stay here... added meanwhile in 3006368211fb1ce33dda1bc2240ac88fd09c5299

**Comment by sofievdbos** [comment]
I'm working on that one & I'll add a PR soon. 🎉

**Comment by sofievdbos** [comment]
Checking before doing a PR: 

> Each poster would open in a new "dedicated" tab or window. Clicking on it again would just lead you to that tab/window if it was already open.

That's not the case anymore? EDIT: I thought you meant the `PDF`. However, you referred to the Jitsi room. 

> You can share your poster window. Jitsi requires a browser extension to provide the ability to share your desktop. We have been using Jitsi happily on Chrome/Chromium for years. Extension link.

The Extension link 1) allows you to schedule Jitsi Meetings & 2) provides calendar integrations to schedule meetings for meet.jit.si site. I don't think you need it to share your desktop (at least I don't need it), which is why I commented it for now.

**Comment by yarikoptic** [comment]
> > Each poster would open in a new "dedicated" tab or window. Clicking on it again would just lead you to that tab/window if it was already open.
> 
> That's not the case anymore? EDIT: I thought you meant the `PDF`. However, you referred to the Jitsi room.

I have just spotted that too -- will implement for posters (PDFs) as well now.

**Comment by yarikoptic** [comment]
> > You can share your poster window. Jitsi requires a browser extension to provide the ability to share your desktop. We have been using Jitsi happily on Chrome/Chromium for years. Extension link.
> 
> The Extension link 1) allows you to schedule Jitsi Meetings & 2) provides calendar integrations to schedule meetings for meet.jit.si site. I don't think you need it to share your desktop (at least I don't), which is why I commented it for now.

Correct about that added functionality!  I guess either jitsi app itself might have become better and not needing extensions to share desktop, or it is OS dependent (in my case it is Debian GNU/Linux).  I have not tested recently on a fresh browser installation/account.  Feel welcome to adjust wording to make it more informative and more factually correct ;)

**Comment by yarikoptic** [comment]
> > That's not the case anymore? EDIT: I thought you meant the `PDF`. However, you referred to the Jitsi room.
> 
> I have just spotted that too -- will implement for posters (PDFs) as well now.

done in 549e28b435e905ad3d80a5f31f768c52f905d491

**Comment by effigies** [comment]
## Screenshots to use in an updated README or CONTRIBUTORS.

1. Open posters-overrides.json

<img width="511" alt="Screen Shot 2020-06-26 at 07 10 27" src="https://user-images.githubusercontent.com/83442/85851214-46361a80-b77c-11ea-89c0-37fa28bc4c88.png">

2. Press edit (pencil) button:
<img width="347" alt="Screen Shot 2020-06-26 at 07 09 44" src="https://user-images.githubusercontent.com/83442/85851234-4cc49200-b77c-11ea-80b4-8109301b1e35.png">

3. Edit:
<img width="570" alt="Screen Shot 2020-06-26 at 07 07 59" src="https://user-images.githubusercontent.com/83442/85851265-56e69080-b77c-11ea-9c1b-f2c15302ccfe.png">

4. Commit to patch branch and open PR:

<img width="685" alt="Screen Shot 2020-06-26 at 07 07 33" src="https://user-images.githubusercontent.com/83442/85851276-5bab4480-b77c-11ea-9681-a0a9d4fb431d.png">

**Comment by sofievdbos** [comment]
I've just created a PR (#69). Feel free to check it out! 😄

**Comment by yarikoptic** [comment]
I will consider it addressed by #69
