### ISSUE TITLE
Mark posters with number of current participants

### ISSUE THREAD

**Issue by effigies** [datalad-datasets/ohbm2020-posters#36]
It should be possible, in principle, for a bot to "join" rooms to determine whether or not anybody is present and how many active participants there are. This would allow people to replicate their usual determination of whether they want to visit a poster based on the number of people crowding around.

**Comment by yarikoptic** [comment]
I was thinking along a similar line... looked into a possible API to just query room from outside but found none (without using the jitsi library). I also worried to not cause a notable impact on the meet.jit.si -- 2000 rooms is quite a number to monitor.

**Comment by yarikoptic** [comment]
If tried for the next year -- then we could have our own jitsi server deployment, and then it would be feasible to perform such queries "locally" on the server.

**Comment by effigies** [comment]
True. Was thinking something like phantomjs to render the DOM might work. @satra and I started playing yesterday but didn't get very far. (At least, I didn't.)

And I think to put a fine point on what you were saying, if anybody does dive into this, we need to be careful to proxy this check somewhere, so that we don't have 2000 people pinging 2000 Jitsi rooms.

**Comment by satra** [comment]
everything pointed to requiring a backend server that run phantomjs, slimerjs, or some such to basically do a rendered html grab to get at the number of participants in the room.

**Comment by yarikoptic** [comment]
yes, some service, which **very gently** pokes at those rooms and updates some .json which our main.js (re)loads once in a while and updates entries with availability.
But even with a gentle poking I am afraid it might quickly run into some guards of a public  meet.jit.si due to inhuman number of connections in its period of time.

**Comment by yarikoptic** [comment]
it could be "crowd sourced" though, if main.js does query for rooms of interest of that visitor (some explicit button/url for each row), pings our service which centralizes collection of that information (with "last-updated" field), which in turn is consumed by main.js to display all known so far information ;)

**Comment by effigies** [comment]
@yarikoptic Would it be possible to throw together a Firefox/Chrome extension where participant could report back?

**Comment by yarikoptic** [comment]
that sounds like a big effort. you think it cannot be done purely via JS? an extension would increase the burden to "contribute".

**Comment by yarikoptic** [comment]
may be @soichih or @vsoch have some immediate ideas on howto do it at JS level?

**Comment by vsoch** [comment]
Most of those booking websites that report current number of visitors are totally fake - I'm not sure how you would accomplish that without a server. What about number of views instead? This is used by journals and similar, and will (sort of) accomplish the same thing to show viewership https://api.altmetric.com/embeds.html.

**Comment by vsoch** [comment]
As a user I wouldn't have incentive to install some custom extension for reporting.

**Comment by yarikoptic** [comment]
Note: if implemented, server should keep the log of visitations, so we could have displayed when people did come/hangout.

**Comment by soichih** [comment]
I can try setting up a websocket server that can keep up with most recently visited users. Then on client side we can subscribe and show counts that updates dynamically? Maybe I can do that in an hour or so..

**Comment by soichih** [comment]
How about something like this? 

![image](https://user-images.githubusercontent.com/923896/85773611-09bade00-b6ec-11ea-9fd9-ad9f596ce6f2.png)

**Comment by vsoch** [comment]
So you are using web sockets, and have a running server?

**Comment by soichih** [comment]
Yes. It's running on my dev server. I just sent a PR. The server is running, so you should be able to test it.

**Comment by vsoch** [comment]
Oh cool! Well if you have a server, you can do anything that you like :) I don't know [how much truth there is to this](https://medium.com/@stestagg/stealing-secrets-from-developers-using-websockets-254f98d577a0) but I'd keep it in mind if this strategy is going to be used.

**Comment by soichih** [comment]
@vsoch that's intersting! Yeah, I've forgotten that ws:// wss:// doesn't provide CORS restriction. I am a bit old school so I don't normally run dev servers on my laptop, but I think this issue applies to *all* socket based servers - not just *web* socket. Although.. that any secret exchanged between dev client and dev server is probably limited to some dev content (no production key, real data, etc..) so I think the motivation of this type of attack is pretty low.. but I could be wrong.

**Comment by yarikoptic** [comment]
Implemented by amazing @soichih and tested in the field! ;)
