### ISSUE TITLE
Load overrides in main.js instead of needing to rerun python script

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#4]
Someone verse in JS and a bit in jquery needs to move this Python code

https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/tools/make_page.py#L63

to somewhere around 

https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/assets/js/main.js#L439

That code should update records loaded from https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/posters.json with what it finds in https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/posters-overrides.json for that poster record.  The whole code/structure is messy/suboptimal but it works!

**Comment by christian-monch** [comment]
Hi @yarikoptic  I think [PR #43 ](https://github.com/datalad-datasets/ohbm2020-posters/pull/43) should do what you intended. Works locally for me.

**Comment by yarikoptic** [comment]
Was done!
