### ISSUE TITLE
Video demonstrations rooms

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#53]
That session is even worse than posters since it is a mix of videos and PDFs, some duplicated etc... I wondered if we could get second page with a table for those with minted rooms?

**Comment by yarikoptic** [comment]
may be it is a non-issue really since probably many (if not most) software demos have posters as well, so people do use the same rooms: see e.g. https://twitter.com/SteMoia/status/1276186840505233409?s=20, but might be useful to annotate explicitly.  ATM search for "software" returns 13, "demo" returns 6 entries

**Comment by christinerogers** [comment]
It's definitely an issue ! (not a non-issue) 
I was coming here to file this...  since we don't have a separate poster && not listed in this repo currently.
Upvote 👍  and how can I help?

**Comment by christinerogers** [comment]
@yarikoptic  here's the specific SoftwareDemo needing a Jitsi link: `qEEGT-CBRAIN for Open Science` author: Bosch-Bayard
https://cdn-akamai.6connex.com//645/1827//OHBM_Qeegt-Cbrain_Poster_2020_15922367208559419.pdf

**Comment by yarikoptic** [comment]
ok, since I do not expect OHBM adjusting that spreadsheet we already use, and to avoid code tuning, I will add this one to original spreadsheet. 
I guess poster number 2020 is not pertinent to OHBM since we do have 2020 poster "A robust processing pipeline for source estimation to MEG spikes"

**Comment by yarikoptic** [comment]
grr though -- we would need code tune up to make it happen due to crummy dirty @yarikoptic 's code .  I will just initiate an additional .json with software demos records we would merge in.  They will have index starting at 10000 ;-)

**Comment by christinerogers** [comment]
thanks!
> I guess poster number 2020 is not pertinent to OHBM since we do have 2020 poster "A robust processing pipeline for source estimation to MEG spikes"

  "poster number" for this software demo is: 2781  (not 2020 :)
`qEEG` ... is the demo name -  a PDF was uploaded for it (that's what that link was)

**Comment by yarikoptic** [comment]
ran out of time for a PR /review, pushed a tentative solution directly with 2781 added.  New additions should go to SoftwareDemos.tsv file

**Comment by yarikoptic** [comment]
although -- will reopen.  W still need to auto-populate it.  PRs against spreadsheet wouldn't work -- conflicts, unless we prepropulate empty rows

**Comment by yarikoptic** [comment]
Ok, we have 38 entries now with a mark shown in "Demo" column
