### ISSUE TITLE
Are we allowed to post thumbnails of each posters? 

### ISSUE THREAD

**Issue by soichih** [datalad-datasets/ohbm2020-posters#60]
Do you think we are allowed to generate thumbnail image of all posters and post them through our site? @effigies 's poster will look like this for example..

> convert -thumbnail x200 -background white poster_15922429379118925.pdf thumb.png

![chris](https://user-images.githubusercontent.com/923896/85805540-a09e8f00-b71a-11ea-8e58-1761de3d1da6.png)

**Comment by effigies** [comment]
Related #37.

If we're allowed to archive the posters, we should be able to thumbnail and/or preview them.

**Comment by soichih** [comment]
I will follow up on #37

**Comment by yarikoptic** [comment]
I think, if anything,  we would ask for forgiveness rather than for permission at this point.
