### ISSUE TITLE
Change poster PDF to add link of video

### ISSUE THREAD

**Issue by usadiqgriffin** [datalad-datasets/ohbm2020-posters#63]
How can I change the poster PDF to add a link to a video description?
Or is there any other way to add video description?

**Comment by htwangtw** [comment]
People are working on a more detailed description. See PR #69 and issue #20.

**Comment by yarikoptic** [comment]
sorry -- for pdf we need url to pdf. if you would like to add additional video - see #56 . reopen if something not in existing issues
