### ISSUE TITLE
Paging is flakey - Option to "show all"?

### ISSUE THREAD

**Issue by nicholst** [datalad-datasets/ohbm2020-posters#65]
When paging through abstracts I find that, randomly, the page view will return to the first page.  Sometimes this is after clicking on a PDF, or sometimes just when scrolling through pages. (Very annoying when you've just moved through a dozen or so pages to find the topics you're interested in).

Maybe there is a way to have the "Show entries" menu include an "all" option?

**Comment by yarikoptic** [comment]
Yeah, we should do that - may be @soichih or @rmarkello know from top of the head howto best?

**Comment by rmarkello** [comment]
Done! See #74 :grin:

**Comment by nicholst** [comment]
Awesome! Thank you! Can't wait to try it out.

**Comment by yarikoptic** [comment]
deployed.
