### ISSUE TITLE
`posters-overrides.json` did not overwrite video chat url

### ISSUE THREAD

**Issue by htwangtw** [datalad-datasets/ohbm2020-posters#75]
On the current website, the video chats are the default jitsi rooms. 
I picked a few from `posters-overrides.json` and `posters.json` to check. The values in these two files are correct, but the website display is not right. I am not entirely sure if this is just a delay of updating the website. I have refreshed the page several times over 5 minutes and the behaviour remains the same.
PDFs are being overwritten correctly. I didn't investigate if other values not being correctly overwritten.

**Comment by yarikoptic** [comment]
oh, thanks!  I guess it was a side-effect of recent enhancement to track... yes
https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/assets/js/main.js#L229

mints urls instead of reusing ... I will look into fixing it now, and if I fail - will ask @soichih for help ;)

**Comment by yarikoptic** [comment]
yes, I failed -- I realized that we store complete html reference in `videochat` field, so it needs to be parsed to extract URL and name of the room to be passed to `openJit`.  Dear @soichih - please help!!!

**Comment by soichih** [comment]
Ah, I forgot about this too. I will update my recent PR.

**Comment by soichih** [comment]
Actually, I think I should wait for https://github.com/datalad-datasets/ohbm2020-posters/pull/43 to get merged before I touch this? 

I am going to update those 6 "videochat" override entry to just contain the jitsi room name (except the one that uses zoom link - we need to implement something similar to what I did with https://github.com/datalad-datasets/ohbm2020-posters/pull/79 with that one. Or can we just ask that they use jitsi instead?

**Comment by htwangtw** [comment]
Yeah I think this is really not an emergency since there are only six entries.
Thanks for picking this up!

**Comment by yarikoptic** [comment]
I think this was fixed in the one of the last PRs.
