### ISSUE TITLE
Shorter than expected "Online" count

### ISSUE THREAD

**Issue by effigies** [datalad-datasets/ohbm2020-posters#84]
In a group of 7, only shows 2. If we wait for a bit, the count drops further.

cc @soichih

**Comment by soichih** [comment]
Did they all opened the room from our list page?

**Comment by soichih** [comment]
I just restarted the ws server and now I am seeing up to 8 people in the room.

![image](https://user-images.githubusercontent.com/923896/85911831-a6b56e00-b7f5-11ea-95e3-2772e86c7892.png)

There might be some issue with how I am broadcasting the update..

**Comment by soichih** [comment]
I just noticed that.. if I have the online count sorted, 1) the whole table flickers when the data is updated 2) which makes it nearly impossible to change page number.. looking into this now.

**Comment by yarikoptic** [comment]
should be closed with a push of an updated backend script @soichih ?
